from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class CatalogPoint:
    """
    Stores one projected Yale catalog star near the image center.
    """

    hr_id: int
    magnitude: float
    x: float
    y: float


@dataclass(frozen=True)
class CentroidPoint:
    """
    Stores one centroid detected from the image.
    """

    obs_id: int
    x: float
    y: float
    brightness: int


@dataclass(frozen=True)
class Transform:
    """
    Stores a 2D similarity transform from catalog plate coordinates to image pixels.
    """

    scale: float
    cos_angle: float
    sin_angle: float
    tx: float
    ty: float


def parse_ra(text: str) -> float | None:
    """
    Converts fixed-width catalog RA text to degrees.
    """

    text = text.strip()
    if len(text) < 6:
        return None
    try:
        return (float(text[:2]) + float(text[2:4]) / 60.0 + float(text[4:]) / 3600.0) * 15.0
    except ValueError:
        return None


def parse_dec(text: str) -> float | None:
    """
    Converts fixed-width catalog DEC text to degrees.
    """

    text = text.strip()
    if len(text) < 6:
        return None
    try:
        sign = -1.0 if text[0] == "-" else 1.0
        body = text[1:] if text[0] in "+-" else text
        return sign * (float(body[:2]) + float(body[2:4]) / 60.0 + float(body[4:]) / 3600.0)
    except ValueError:
        return None


def load_catalog_points(catalog_path: Path, center_ra_deg: float, center_dec_deg: float, image_size: int, fov_deg: float) -> list[CatalogPoint]:
    """
    Projects nearby catalog stars into a simple north-up tangent-plane pixel frame.
    """

    points: list[CatalogPoint] = []
    pixels_per_degree = image_size / fov_deg
    for line in catalog_path.read_text(errors="ignore").splitlines():
        try:
            hr_id = int(line[:4])
            ra_deg = parse_ra(line[75:83])
            dec_deg = parse_dec(line[83:90])
            magnitude = float(line[102:107])
        except ValueError:
            continue
        if ra_deg is None or dec_deg is None or magnitude > 8.0:
            continue
        delta_ra_deg = ((ra_deg - center_ra_deg + 180.0) % 360.0) - 180.0
        projected_x = image_size * 0.5 + delta_ra_deg * math.cos(math.radians(center_dec_deg)) * pixels_per_degree
        projected_y = image_size * 0.5 - (dec_deg - center_dec_deg) * pixels_per_degree
        if -image_size <= projected_x <= image_size * 2 and -image_size <= projected_y <= image_size * 2:
            points.append(CatalogPoint(hr_id, magnitude, projected_x, projected_y))
    return points


def load_centroids(stars_csv_path: Path) -> list[CentroidPoint]:
    """
    Reads centroid CSV rows generated by the Centroid executable.
    """

    points: list[CentroidPoint] = []
    with stars_csv_path.open(newline="") as file:
        for row in csv.DictReader(file):
            points.append(CentroidPoint(int(row["index"]) - 1, float(row["x"]), float(row["y"]), int(row["brightness"])))
    return points


def transform_point(transform: Transform, x: float, y: float) -> tuple[float, float]:
    """
    Applies a similarity transform to one catalog point.
    """

    return (
        transform.scale * (transform.cos_angle * x - transform.sin_angle * y) + transform.tx,
        transform.scale * (transform.sin_angle * x + transform.cos_angle * y) + transform.ty,
    )


def transform_from_pairs(first_catalog: CatalogPoint, second_catalog: CatalogPoint, first_centroid: CentroidPoint, second_centroid: CentroidPoint) -> Transform | None:
    """
    Estimates a similarity transform from two catalog-to-centroid pair assignments.
    """

    catalog_dx = second_catalog.x - first_catalog.x
    catalog_dy = second_catalog.y - first_catalog.y
    centroid_dx = second_centroid.x - first_centroid.x
    centroid_dy = second_centroid.y - first_centroid.y
    catalog_distance = math.hypot(catalog_dx, catalog_dy)
    centroid_distance = math.hypot(centroid_dx, centroid_dy)
    if catalog_distance < 1.0 or centroid_distance < 1.0:
        return None
    scale = centroid_distance / catalog_distance
    cos_angle = (catalog_dx * centroid_dx + catalog_dy * centroid_dy) / (catalog_distance * centroid_distance)
    sin_angle = (catalog_dx * centroid_dy - catalog_dy * centroid_dx) / (catalog_distance * centroid_distance)
    rotated_x = scale * (cos_angle * first_catalog.x - sin_angle * first_catalog.y)
    rotated_y = scale * (sin_angle * first_catalog.x + cos_angle * first_catalog.y)
    return Transform(scale, cos_angle, sin_angle, first_centroid.x - rotated_x, first_centroid.y - rotated_y)


def score_transform(transform: Transform, catalog_points: list[CatalogPoint], centroids: list[CentroidPoint], tolerance_px: float) -> tuple[int, float, list[tuple[int, int, float]]]:
    """
    Counts nearest-neighbor catalog-to-centroid matches for one transform.
    """

    matches: list[tuple[int, int, float]] = []
    used_obs_ids: set[int] = set()
    for catalog_point in sorted(catalog_points, key=lambda point: point.magnitude):
        projected_x, projected_y = transform_point(transform, catalog_point.x, catalog_point.y)
        nearest = min(centroids, key=lambda point: (point.x - projected_x) ** 2 + (point.y - projected_y) ** 2)
        distance = math.hypot(nearest.x - projected_x, nearest.y - projected_y)
        if distance <= tolerance_px and nearest.obs_id not in used_obs_ids:
            used_obs_ids.add(nearest.obs_id)
            matches.append((catalog_point.hr_id, nearest.obs_id, distance))
    mean_error = sum(match[2] for match in matches) / len(matches) if matches else 1e9
    return len(matches), mean_error, matches


def find_best_transform(
    catalog_points: list[CatalogPoint],
    centroids: list[CentroidPoint],
    tolerance_px: float,
    min_scale: float,
    max_scale: float,
) -> tuple[Transform | None, list[tuple[int, int, float]]]:
    """
    Brute-forces two-star assignments to find the best actual-image plate transform.
    """

    best_transform: Transform | None = None
    best_matches: list[tuple[int, int, float]] = []
    best_key = (-1, 1e9)
    bright_catalog = sorted(catalog_points, key=lambda point: point.magnitude)[:25]
    for first_catalog_index, first_catalog in enumerate(bright_catalog):
        for second_catalog in bright_catalog[first_catalog_index + 1 :]:
            for first_centroid in centroids:
                for second_centroid in centroids:
                    if first_centroid.obs_id == second_centroid.obs_id:
                        continue
                    transform = transform_from_pairs(first_catalog, second_catalog, first_centroid, second_centroid)
                    if transform is None or not min_scale <= transform.scale <= max_scale:
                        continue
                    count, mean_error, matches = score_transform(transform, catalog_points, centroids, tolerance_px)
                    key = (count, -mean_error)
                    if key > best_key:
                        best_key = key
                        best_transform = transform
                        best_matches = matches
    return best_transform, best_matches


def main() -> None:
    """
    Reports whether the actual image centroids align with the expected SkyView center.
    """

    parser = argparse.ArgumentParser()
    parser.add_argument("--stars", required=True, type=Path)
    parser.add_argument("--catalog", default=PROJECT_ROOT / "data" / "catalog.bin", type=Path)
    parser.add_argument("--center-ra", default=(10 + 16 / 60 + 56 / 3600) * 15, type=float)
    parser.add_argument("--center-dec", default=59 + 51 / 60 + 22 / 3600, type=float)
    parser.add_argument("--image-size", default=877, type=int)
    parser.add_argument("--fov", default=10.0, type=float)
    parser.add_argument("--tolerance-px", default=35.0, type=float)
    parser.add_argument("--min-scale", default=0.5, type=float)
    parser.add_argument("--max-scale", default=2.0, type=float)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    catalog_points = load_catalog_points(args.catalog, args.center_ra, args.center_dec, args.image_size, args.fov)
    centroids = load_centroids(args.stars)
    transform, matches = find_best_transform(catalog_points, centroids, args.tolerance_px, args.min_scale, args.max_scale)
    print(f"catalog_points={len(catalog_points)} centroids={len(centroids)}")
    if transform is None:
        print("matched=false")
        return
    rotation_deg = math.degrees(math.atan2(transform.sin_angle, transform.cos_angle))
    mean_error = sum(match[2] for match in matches) / len(matches) if matches else float("nan")
    print(f"matched_count={len(matches)} mean_error_px={mean_error:.2f} scale={transform.scale:.4f} rotation_deg={rotation_deg:.2f}")
    for hr_id, obs_id, distance_px in matches:
        print(f"match hr={hr_id} obs={obs_id} error_px={distance_px:.2f}")
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with args.output.open("w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(["hr_id", "obs_id", "error_px"])
            writer.writerows(matches)
        print(f"wrote_csv={args.output}")


if __name__ == "__main__":
    main()
