from __future__ import annotations

import argparse
import csv
import html
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXE = PROJECT_ROOT / "C" / "build-generated-release" / "demo_centroid_compare.exe"
DEFAULT_OUTPUT = PROJECT_ROOT / "outputs" / "c_identifier_matches.svg"


@dataclass(frozen=True)
class CentroidRow:
    """
    Stores one centroid row from the CSV generated by the Centroid executable.
    """

    obs_id: int
    x: float
    y: float
    brightness: int


@dataclass(frozen=True)
class MatchRow:
    """
    Stores one algorithm match parsed from the C identifier output.
    """

    algorithm: str
    obs_id: int
    hr_id: int
    residual_arcsec: int


def parse_args() -> argparse.Namespace:
    """
    Parses command-line arguments for running and visualizing the C identifier.
    """

    parser = argparse.ArgumentParser()
    parser.add_argument("--stars", required=True, type=Path)
    parser.add_argument("--image", type=Path)
    parser.add_argument("--width", required=True, type=int)
    parser.add_argument("--height", required=True, type=int)
    parser.add_argument("--fov", required=True, type=float)
    parser.add_argument("--exe", default=DEFAULT_EXE, type=Path)
    parser.add_argument("--output", default=DEFAULT_OUTPUT, type=Path)
    return parser.parse_args()


def read_centroids(stars_csv_path: Path) -> list[CentroidRow]:
    """
    Reads centroid rows and converts CSV row numbers to zero-based observed IDs.
    """

    rows: list[CentroidRow] = []
    with stars_csv_path.open(newline="") as file:
        for row in csv.DictReader(file):
            rows.append(
                CentroidRow(
                    obs_id=int(row["index"]) - 1,
                    x=float(row["x"]),
                    y=float(row["y"]),
                    brightness=int(row["brightness"]),
                )
            )
    return rows


def run_identifier(executable_path: Path, stars_csv_path: Path, width: int, height: int, fov: float) -> str:
    """
    Runs the C identifier and returns stdout for parsing and audit.
    """

    command = [str(executable_path), str(stars_csv_path), str(width), str(height), str(fov)]
    completed = subprocess.run(command, cwd=PROJECT_ROOT, check=True, text=True, capture_output=True)
    return completed.stdout


def parse_matches(identifier_stdout: str) -> list[MatchRow]:
    """
    Parses `Algorithm match,obs_id,hr_id,residual_arcsec` rows from C stdout.
    """

    matches: list[MatchRow] = []
    pattern = re.compile(r"^(TETRA|Pyramid) match,(\d+),(\d+),(\d+)$")
    for line in identifier_stdout.splitlines():
        parsed = pattern.match(line.strip())
        if parsed is None:
            continue
        matches.append(
            MatchRow(
                algorithm=parsed.group(1),
                obs_id=int(parsed.group(2)),
                hr_id=int(parsed.group(3)),
                residual_arcsec=int(parsed.group(4)),
            )
        )
    return matches


def plot_matches(
    centroids: list[CentroidRow],
    matches: list[MatchRow],
    image_path: Path | None,
    output_path: Path,
    width: int,
    height: int,
) -> None:
    """
    Draws detected centroids and algorithm-specific matched HR IDs as dependency-free SVG.
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    svg_lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<style>text{font-family:Consolas,monospace;font-size:12px}.label{paint-order:stroke;stroke:#000;stroke-width:3px;stroke-linejoin:round}</style>',
    ]
    if image_path is not None:
        image_href = html.escape(str(image_path.resolve()))
        svg_lines.append(f'<image href="{image_href}" x="0" y="0" width="{width}" height="{height}" />')
    else:
        svg_lines.append(f'<rect x="0" y="0" width="{width}" height="{height}" fill="#111" />')

    for centroid in centroids:
        svg_lines.append(
            f'<circle cx="{centroid.x:.2f}" cy="{centroid.y:.2f}" r="3" fill="white" stroke="black" stroke-width="1" />'
        )
        svg_lines.append(
            f'<text class="label" x="{centroid.x + 5:.2f}" y="{centroid.y + 5:.2f}" fill="white">{centroid.obs_id}</text>'
        )

    color_by_algorithm = {"TETRA": "red", "Pyramid": "cyan"}
    centroid_by_id = {centroid.obs_id: centroid for centroid in centroids}
    for match in matches:
        centroid = centroid_by_id.get(match.obs_id)
        if centroid is None:
            continue
        color = color_by_algorithm.get(match.algorithm, "yellow")
        svg_lines.append(
            f'<circle cx="{centroid.x:.2f}" cy="{centroid.y:.2f}" r="14" fill="none" stroke="{color}" stroke-width="3" />'
        )
        svg_lines.append(
            f'<text class="label" x="{centroid.x + 10:.2f}" y="{centroid.y - 14:.2f}" fill="{color}">'
            f'{match.algorithm[0]} HR{match.hr_id}</text>'
        )
        svg_lines.append(
            f'<text class="label" x="{centroid.x + 10:.2f}" y="{centroid.y:.2f}" fill="{color}">'
            f'{match.residual_arcsec}&quot;</text>'
        )

    svg_lines.append("</svg>")
    output_path.write_text("\n".join(svg_lines), encoding="utf-8")


def main() -> None:
    """
    Runs the C identifier, prints its attitude output, and saves a centroid match plot.
    """

    args = parse_args()
    centroids = read_centroids(args.stars)
    identifier_stdout = run_identifier(args.exe, args.stars, args.width, args.height, args.fov)
    matches = parse_matches(identifier_stdout)
    plot_matches(centroids, matches, args.image, args.output, args.width, args.height)
    print(identifier_stdout)
    print(f"Saved visualization: {args.output}")


if __name__ == "__main__":
    main()
